// This file centralizes the definition of all available tools, organized by category.
export const categories = [
  {
    name: 'Ferramentas populares',
    tools: [
      {
        id: 'multi-tool',
        name: 'Ferramenta completa de PDF',
        icon: 'pencil-ruler',
        subtitle:
          'Unir, dividir, organizar, excluir, girar, adicionar páginas em branco, extrair e duplicar em uma única interface.',
      },
      {
        id: 'merge',
        name: 'Unir PDF',
        icon: 'combine',
        subtitle: 'Combine vários PDFs em um único arquivo.',
      },
      {
        id: 'split',
        name: 'Dividir PDF',
        icon: 'scissors',
        subtitle: 'Separe um intervalo de páginas em um novo PDF.',
      },
      {
        id: 'compress',
        name: 'Comprimir PDF',
        icon: 'zap',
        subtitle: 'Reduza o tamanho do arquivo sem perder qualidade.',
      },
      {
        id: 'edit',
        name: 'Editor de PDF',
        icon: 'pocket-knife',
        subtitle:
          'Anote, destaque, oculte informações, comente, adicione formas/imagens, pesquise e visualize PDFs.',
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG para PDF',
        icon: 'image-up',
        subtitle: 'Crie um PDF a partir de uma ou mais imagens JPG.',
      },
      {
        id: 'sign-pdf',
        name: 'Assinar PDF',
        icon: 'pen-tool',
        subtitle: 'Desenhe, digite ou envie sua assinatura.',
      },
      {
        id: 'cropper',
        name: 'Cortar PDF',
        icon: 'crop',
        subtitle: 'Ajuste as margens de cada página do PDF.',
      },
      {
        id: 'extract-pages',
        name: 'Extrair páginas',
        icon: 'ungroup',
        subtitle: 'Salve um conjunto de páginas como novos arquivos.',
      },
      {
        id: 'duplicate-organize',
        name: 'Duplicar e organizar',
        icon: 'files',
        subtitle: 'Duplique, reordene e exclua páginas.',
      },
      {
        id: 'delete-pages',
        name: 'Excluir páginas',
        icon: 'trash-2',
        subtitle: 'Remova páginas específicas do documento.',
      },
    ],
  },
  {
    name: 'Editar e anotar',
    tools: [
      {
        id: 'edit',
        name: 'Editor de PDF',
        icon: 'pocket-knife',
        subtitle:
          'Anote, destaque, oculte informações, comente, adicione formas/imagens, pesquise e visualize PDFs.',
      },
      {
        id: 'bookmark-pdf',
        name: 'Editar marcadores',
        icon: 'bookmark',
        subtitle: 'Adicione, edite, importe, exclua e extraia marcadores de PDF.',
      },
      {
        id: 'table-of-contents',
        name: 'Tabela de conteúdo',
        icon: 'list',
        subtitle: 'Gere uma página de sumário a partir dos marcadores.',
      },
      {
        id: 'add-page-numbers',
        name: 'Numeração de páginas',
        icon: 'list-ordered',
        subtitle: 'Insira números de página com o formato desejado.',
      },
      {
        id: 'add-watermark',
        name: 'Adicionar marca d’água',
        icon: 'droplets',
        subtitle: 'Aplique texto ou imagem sobre as páginas do PDF.',
      },
      {
        id: 'add-header-footer',
        name: 'Cabeçalho e rodapé',
        icon: 'pilcrow',
        subtitle: 'Inclua texto na parte superior e inferior das páginas.',
      },
      {
        id: 'invert-colors',
        name: 'Inverter cores',
        icon: 'contrast',
        subtitle: 'Crie uma versão “modo escuro” do seu PDF.',
      },
      {
        id: 'change-background-color',
        name: 'Cor de fundo',
        icon: 'palette',
        subtitle: 'Altere a cor de fundo do PDF.',
      },
      {
        id: 'change-text-color',
        name: 'Cor do texto',
        icon: 'type',
        subtitle: 'Mude a cor do texto no documento.',
      },
      {
        id: 'sign-pdf',
        name: 'Assinar PDF',
        icon: 'pen-tool',
        subtitle: 'Desenhe, digite ou envie sua assinatura.',
      },
      {
        id: 'remove-annotations',
        name: 'Remover anotações',
        icon: 'eraser',
        subtitle: 'Remova comentários, destaques e links.',
      },
      {
        id: 'cropper',
        name: 'Cortar PDF',
        icon: 'crop',
        subtitle: 'Ajuste as margens de cada página do PDF.',
      },
      {
        id: 'form-filler',
        name: 'Preencher formulários',
        icon: 'square-pen',
        subtitle: 'Preencha formulários diretamente no navegador.',
      },
      {
        id: 'remove-blank-pages',
        name: 'Remover páginas em branco',
        icon: 'file-minus-2',
        subtitle: 'Detecte e exclua páginas vazias automaticamente.',
      },
    ],
  },
  {
    name: 'Converter para PDF',
    tools: [
      {
        id: 'image-to-pdf',
        name: 'Imagens para PDF',
        icon: 'images',
        subtitle: 'Combine diferentes imagens em um único PDF.',
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG para PDF',
        icon: 'image-up',
        subtitle: 'Crie um PDF a partir de uma ou mais imagens JPG.',
      },
      {
        id: 'png-to-pdf',
        name: 'PNG para PDF',
        icon: 'image-up',
        subtitle: 'Crie um PDF a partir de imagens PNG.',
      },
      {
        id: 'webp-to-pdf',
        name: 'WebP para PDF',
        icon: 'image-up',
        subtitle: 'Crie um PDF a partir de imagens WebP.',
      },
      {
        id: 'svg-to-pdf',
        name: 'SVG para PDF',
        icon: 'pen-tool',
        subtitle: 'Crie um PDF a partir de arquivos SVG.',
      },
      {
        id: 'bmp-to-pdf',
        name: 'BMP para PDF',
        icon: 'image',
        subtitle: 'Crie um PDF a partir de imagens BMP.',
      },
      {
        id: 'heic-to-pdf',
        name: 'HEIC para PDF',
        icon: 'smartphone',
        subtitle: 'Crie um PDF a partir de imagens HEIC.',
      },
      {
        id: 'tiff-to-pdf',
        name: 'TIFF para PDF',
        icon: 'layers',
        subtitle: 'Crie um PDF a partir de imagens TIFF.',
      },
      {
        id: 'txt-to-pdf',
        name: 'Texto para PDF',
        icon: 'file-pen',
        subtitle: 'Converta um arquivo de texto simples em PDF.',
      },
      {
        id: 'json-to-pdf',
        name: 'JSON para PDF',
        icon: 'file-code',
        subtitle: 'Converta arquivos JSON para PDF.',
      },
    ],
  },
  {
    name: 'Converter de PDF',
    tools: [
      {
        id: 'pdf-to-jpg',
        name: 'PDF para JPG',
        icon: 'file-image',
        subtitle: 'Transforme cada página em uma imagem JPG.',
      },
      {
        id: 'pdf-to-png',
        name: 'PDF para PNG',
        icon: 'file-image',
        subtitle: 'Transforme cada página em uma imagem PNG.',
      },
      {
        id: 'pdf-to-webp',
        name: 'PDF para WebP',
        icon: 'file-image',
        subtitle: 'Transforme cada página em uma imagem WebP.',
      },
      {
        id: 'pdf-to-bmp',
        name: 'PDF para BMP',
        icon: 'file-image',
        subtitle: 'Transforme cada página em uma imagem BMP.',
      },
      {
        id: 'pdf-to-tiff',
        name: 'PDF para TIFF',
        icon: 'file-image',
        subtitle: 'Transforme cada página em uma imagem TIFF.',
      },
      {
        id: 'pdf-to-greyscale',
        name: 'PDF para tons de cinza',
        icon: 'palette',
        subtitle: 'Converta todas as cores para preto e branco.',
      },
      {
        id: 'pdf-to-json',
        name: 'PDF para JSON',
        icon: 'file-code',
        subtitle: 'Converta arquivos PDF em JSON.',
      },
    ],
  },
  {
    name: 'Organizar e gerenciar',
    tools: [
      {
        id: 'ocr-pdf',
        name: 'OCR em PDF',
        icon: 'scan-text',
        subtitle: 'Deixe um PDF pesquisável e copiável.',
      },
      {
        id: 'merge',
        name: 'Unir PDF',
        icon: 'combine',
        subtitle: 'Combine vários PDFs em um único arquivo.',
      },
      {
        id: 'alternate-merge',
        name: 'Mesclar alternando páginas',
        icon: 'shuffle',
        subtitle: 'Una PDFs alternando páginas de cada documento.',
      },
      {
        id: 'organize',
        name: 'Organizar PDF',
        icon: 'grip',
        subtitle: 'Reordene páginas arrastando e soltando.',
      },
      {
        id: 'duplicate-organize',
        name: 'Duplicar e organizar',
        icon: 'files',
        subtitle: 'Duplique, reordene e exclua páginas.',
      },
      {
        id: 'add-attachments',
        name: 'Adicionar anexos',
        icon: 'paperclip',
        subtitle: 'Incorpore arquivos dentro do PDF.',
      },
      {
        id: 'extract-attachments',
        name: 'Extrair anexos',
        icon: 'download',
        subtitle: 'Extraia todos os anexos do PDF em um ZIP.',
      },
      {
        id: 'edit-attachments',
        name: 'Editar anexos',
        icon: 'file-edit',
        subtitle: 'Visualize ou remova anexos do PDF.',
      },
      {
        id: 'multi-tool',
        name: 'Ferramenta completa de PDF',
        icon: 'pencil-ruler',
        subtitle: 'Editor completo com gerenciamento de páginas.',
      },
      {
        id: 'split',
        name: 'Dividir PDF',
        icon: 'scissors',
        subtitle: 'Separe um intervalo de páginas em um novo PDF.',
      },
      {
        id: 'split-in-half',
        name: 'Dividir páginas ao meio',
        icon: 'table-columns-split',
        subtitle: 'Divida páginas horizontal ou verticalmente.',
      },
      {
        id: 'extract-pages',
        name: 'Extrair páginas',
        icon: 'ungroup',
        subtitle: 'Salve um conjunto de páginas como novos arquivos.',
      },
      {
        id: 'delete-pages',
        name: 'Excluir páginas',
        icon: 'trash-2',
        subtitle: 'Remova páginas específicas do documento.',
      },
      {
        id: 'add-blank-page',
        name: 'Adicionar página em branco',
        icon: 'file-plus-2',
        subtitle: 'Insira uma página vazia em qualquer posição.',
      },
      {
        id: 'reverse-pages',
        name: 'Inverter ordem',
        icon: 'arrow-down-z-a',
        subtitle: 'Inverta a ordem de todas as páginas.',
      },
      {
        id: 'rotate',
        name: 'Girar PDF',
        icon: 'rotate-cw',
        subtitle: 'Gire páginas em incrementos de 90°.',
      },
      {
        id: 'n-up',
        name: 'N páginas em 1',
        icon: 'layout-grid',
        subtitle: 'Monte várias páginas em uma única folha.',
      },
      {
        id: 'combine-single-page',
        name: 'Unir em uma página',
        icon: 'unfold-vertical',
        subtitle: 'Junte todas as páginas em um scroll contínuo.',
      },
      {
        id: 'view-metadata',
        name: 'Ver metadados',
        icon: 'info',
        subtitle: 'Inspecione as propriedades ocultas do PDF.',
      },
      {
        id: 'edit-metadata',
        name: 'Editar metadados',
        icon: 'file-cog',
        subtitle: 'Altere autor, título e outras propriedades.',
      },
      {
        id: 'pdf-to-zip',
        name: 'PDFs para ZIP',
        icon: 'stretch-horizontal',
        subtitle: 'Agrupe vários PDFs em um arquivo ZIP.',
      },
      {
        id: 'compare-pdfs',
        name: 'Comparar PDFs',
        icon: 'git-compare',
        subtitle: 'Compare dois PDFs lado a lado.',
      },
      {
        id: 'posterize',
        name: 'Posterizar PDF',
        icon: 'notepad-text-dashed',
        subtitle: 'Divida uma página grande em várias menores.',
      },
    ],
  },
  {
    name: 'Otimizar e corrigir',
    tools: [
      {
        id: 'compress',
        name: 'Comprimir PDF',
        icon: 'zap',
        subtitle: 'Reduza o tamanho do arquivo sem perder qualidade.',
      },
      {
        id: 'fix-dimensions',
        name: 'Padronizar dimensões',
        icon: 'ruler-dimension-line',
        subtitle: 'Aplique o mesmo tamanho a todas as páginas.',
      },
      {
        id: 'linearize',
        name: 'Linearizar PDF',
        icon: 'gauge',
        subtitle: 'Otimize o PDF para carregamento rápido na web.',
      },
      {
        id: 'page-dimensions',
        name: 'Dimensões das páginas',
        icon: 'ruler',
        subtitle: 'Analise tamanho, orientação e unidades das páginas.',
      },
      {
        id: 'remove-restrictions',
        name: 'Remover restrições',
        icon: 'unlink',
        subtitle:
          'Remova senhas e bloqueios de PDFs protegidos ou assinados.',
      },
    ],
  },
  {
    name: 'Proteger PDF',
    tools: [
      {
        id: 'encrypt',
        name: 'Proteger com senha',
        icon: 'lock',
        subtitle: 'Bloqueie o PDF adicionando uma senha.',
      },
      {
        id: 'sanitize-pdf',
        name: 'Higienizar PDF',
        icon: 'brush-cleaning',
        subtitle: 'Remova metadados, anotações, scripts e muito mais.',
      },
      {
        id: 'decrypt',
        name: 'Remover senha',
        icon: 'unlock',
        subtitle: 'Usando a senha atual, crie uma cópia sem senha do PDF.',
      },
      {
        id: 'flatten',
        name: 'Achatar PDF',
        icon: 'layers',
        subtitle: 'Transforme campos e anotações em conteúdo fixo.',
      },
      {
        id: 'remove-metadata',
        name: 'Remover metadados',
        icon: 'file-x',
        subtitle: 'Apague dados ocultos do PDF.',
      },
      {
        id: 'change-permissions',
        name: 'Permissões do PDF',
        icon: 'shield-check',
        subtitle: 'Defina ou altere as permissões de uso do PDF.',
      },
    ],
  },
];
